# See https://gist.github.com/chillu/5262316 for setup details

language: php 
php: 
 - 5.3

env:
 - DB=MYSQL CORE_RELEASE=3.0
 - DB=PGSQL CORE_RELEASE=3.0

matrix:
  include:
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3.0

before_script:
 - pear -q install --onlyreqdeps pear/PHP_CodeSniffer
 - phpenv rehash
 - ./tests/travis/travis_setup.php --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - phpunit translatable/tests/
 - phpcs --encoding=utf-8 --tab-width=4 --standard=translatable/tests/phpcs -np translatable
