# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

language: php 
php: 
 - 5.3

env:
  global:
    - GITHUB_API_TOKEN=2434108664388ca0199319b98a6068af8e5dc547
  matrix:
    - DB=MYSQL CORE_RELEASE=3.0
    - DB=PGSQL CORE_RELEASE=3.0

matrix:
  include:
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3.0

before_script:
 - pear -q install --onlyreqdeps pear/PHP_CodeSniffer
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - phpunit translatable/tests/
 - phpcs --encoding=utf-8 --tab-width=4 --standard=translatable/tests/phpcs -np translatable
